name: Test CI
on:
  push:
    branches: [ main, realiteAugmente ]
  pull_request:
    branches: [ main, realiteAugmente]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.6'
      - name: Build apk
        run: |
          flutter pub get
          flutter test
          flutter build apk